@@startuml

skinparam object {
    BackgroundColor<<Observation>> LawnGreen
    BackgroundColor<<DiagnosticReport>> Aqua
    BackgroundColor<<ServiceRequest>> LightSalmon
    BackgroundColor<<Task>> DeepSkyBlue
}

object GenomicsReport << DiagnosticReport >>
object GenomicResults << Observation >>
object Specimen
object RequestForGenomicsTest << ServiceRequest >>
object SupportingInformation << multiple >> {
    observations
    risk assessments
    family member history
    document reference
}
object Patient
object RiskAssessment
object RecommendedActions << Task >>

GenomicsReport --> "0..*" GenomicResults : results
GenomicsReport --> "0..*" Specimen: specimen
GenomicsReport --> "0..1" Patient: subject
GenomicsReport --> "0..*" RequestForGenomicsTest: basedOn
GenomicsReport --> "0..*" SupportingInformation: extension(supporting-info)
GenomicsReport --> "0..*" RiskAssessment: extension(diagnostic-report-risk)
GenomicsReport --> "0..*" RecommendedActions: extension(recommended-action)

RequestForGenomicsTest --> "0..*" Specimen: specimen
RequestForGenomicsTest --> "0..*" SupportingInformation: supportingInfo
RequestForGenomicsTest --> "1..1" Patient: subject

GenomicResults --> "0..1" Specimen: specimen
GenomicResults --> "0..1" Patient: subject

RecommendedActions --> "0..1" GenomicResults :reasonReference
RecommendedActions --> "0..1" Patient: for

@@enduml