@@startuml

skinparam object {
    BackgroundColor<<Observation>> LawnGreen
    BackgroundColor<<DiagnosticReport>> Aqua
    BackgroundColor<<ServiceRequest>> LightSalmon
    BackgroundColor<<Task>> DeepSkyBlue
}

together {
    abstract GenomicFinding << Observation >> #LawnGreen;line.bold {
        component[cytogenetic-location]: 48001-2 [0..*]
        component[gene-studied]: 448018-6 [0..*]
        component[reference-sequence-assembly]: 62374-4 [0..*]
    }
    object Genotype << Observation >> {
        code: 84413-4
    }
    object Haplotype << Observation >> {
        code: 84414-2
    }
    object Variant << Observation >> {
        code: 69548-6
    }
    object SequencePhaseRelationship << Observation >> { 
        code: 82120-7
        valueCodeableConcept: [CIS, TRANS, UNKNOWN]
    }
}
object MolecularSequence

Genotype --|> GenomicFinding
Haplotype --|> GenomicFinding
Variant --|> GenomicFinding

Genotype --> "0..*" Haplotype : derivedFrom
Haplotype --> "0..*" Haplotype : derivedFrom
Genotype --> "0..*" Variant : derivedFrom
Haplotype --> "0..*" Variant : derivedFrom
SequencePhaseRelationship --> "0..*" Haplotype : derivedFrom
SequencePhaseRelationship --> "0..*" Variant : derivedFrom
SequencePhaseRelationship --> "0..*" MolecularSequence : derivedFrom

hide methods

@@enduml