@@startuml

skinparam object {
    BackgroundColor<<Observation>> LawnGreen
    BackgroundColor<<DiagnosticReport>> Aqua
    BackgroundColor<<ServiceRequest>> LightSalmon
    BackgroundColor<<Task>> DeepSkyBlue
}

object GenomicsReport << DiagnosticReport >> #Aqua
together {
    object Grouper << Observation >>
    object OverallInterpretation << Observation >>
    object RegionStudied << Observation >>
    abstract GenomicFindings << Observation >>
    abstract GenomicImplications << Observation >>
}
object RecommendActions << Task >> #RoyalBlue
object others << Observation >>

GenomicsReport --> "0..*" Grouper : "results"
GenomicsReport --> "0..1" OverallInterpretation : "results"
GenomicsReport --> "0..*" GenomicFindings : "results"
GenomicsReport --> "0..*" GenomicImplications : "results"
GenomicsReport --> "0..*" RegionStudied : "results"
GenomicsReport --> "0..*" RecommendActions : "extension(RecommendedActions)"
GenomicsReport --> "0..*" others : "results"

Grouper --> "0..*" Grouper : "hasMember"
Grouper --> "0..*" GenomicFindings : "hasMember"
Grouper --> "0..*" GenomicImplications : "hasMember"
Grouper --> "0..*" RegionStudied : "hasMember"
Grouper --> "0..*" others : "hasMember"

@@enduml
