// Code Systems
Alias: $LNC = http://loinc.org
Alias: $SCT = http://snomed.info/sct
Alias: $UCUM = http://unitsofmeasure.org
Alias: $NCIT = http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl
Alias: $ICD10CM = http://hl7.org/fhir/sid/icd-10-cm
Alias: $RXN = http://www.nlm.nih.gov/research/umls/rxnorm
Alias: $CLINVAR = http://www.ncbi.nlm.nih.gov/clinvar
Alias: $IDTYPE = http://terminology.hl7.org/CodeSystem/v2-0203
Alias: $HGNCID = 	http://www.genenames.org
Alias: $HGNCGROUP = http://www.genenames.org/genegroup
Alias: $HGVS = http://varnomen.hgvs.org
Alias: $SPECIMENTYPE = http://terminology.hl7.org/CodeSystem/v2-0487
Alias: $SEQONT = http://www.sequenceontology.org
Alias: $OBSCAT = http://terminology.hl7.org/CodeSystem/observation-category
Alias: $OBSINT = http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation
Alias: $DIAGNOSTICSERVICE = http://terminology.hl7.org/CodeSystem/v2-0074
Alias: $TASKSTATUS = http://hl7.org/fhir/task-status
Alias: $TASKINTENT = http://hl7.org/fhir/task-intent
Alias: $REQUESTINTENT = http://hl7.org/fhir/request-intent
Alias: $REQUESTSTATUS = http://hl7.org/fhir/request-status
Alias: $RISKQUAL = 	http://terminology.hl7.org/CodeSystem/risk-probability
Alias: $NCTTRIAL = http://clinicaltrials.gov
Alias: $HPO = http://human-phenotype-ontology.org
Alias: $NCBIREFSEQ = http://www.ncbi.nlm.nih.gov/refseq
Alias: $HLAALLELE = http://www.ebi.ac.uk/ipd/imgt/hla
Alias: $GLSTRING = http://glstring.org
Alias: $PHARMVAR = http://www.pharmvar.org
Alias: $SNP = http://www.ncbi.nlm.nih.gov/projects/SNP
Alias: $ISCN = https://iscn.karger.com //defined in THO with https
Alias: $PARTICIPATIONTYPE = http://terminology.hl7.org/CodeSystem/v3-ParticipationType
Alias: $CONFIDENTIALITY = http://terminology.hl7.org/CodeSystem/v3-Confidentiality
Alias: $MONDO = http://purl.obolibrary.org/obo/mondo.owl

//Extensions
Alias: $operation-allowed-type = http://hl7.org/fhir/StructureDefinition/operationdefinition-profile
Alias: $workflow-relatedArtifact = http://hl7.org/fhir/StructureDefinition/workflow-relatedArtifact
Alias: $supporting-info = http://hl7.org/fhir/StructureDefinition/workflow-supportingInfo
Alias: $hla-genotyping-results-allele-database = http://hl7.org/fhir/StructureDefinition/hla-genotyping-results-allele-database
Alias: $hla-genotyping-results-glstring = http://hl7.org/fhir/StructureDefinition/hla-genotyping-results-glstring
