Instance: CGBundleExamplediagnosticreport-pgxexample
InstanceOf: Bundle
Description: "Example for Bundle. "
* entry[0].fullUrl = "http://example.org/fhir/DiagnosticReport/pgx-report"
* entry[0].request.method = #POST
* entry[0].request.url = "DiagnosticReport"
* entry[0].resource.basedOn.reference = "ServiceRequest/pgx-request"
* entry[0].resource.code.coding = http://loinc.org#81247-9
* entry[0].resource.effectiveDateTime = "2016"
* entry[0].resource.extension.url = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/RecommendedAction"
* entry[0].resource.extension.valueReference.reference = "Task/med-usage-impact-task-pgx-example"
* entry[0].resource.id = "pgx-report"
* entry[0].resource.issued = "2018-03-06T00:00:00-05:00"
* entry[0].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/genomics-report"
* entry[0].resource.performer.reference = "Organization/lab"
* entry[0].resource.resourceType = "DiagnosticReport"
* entry[0].resource.result[0].display = "genetics impact for medication metabolism accessment"
* entry[0].resource.result[0].reference = "Observation/med-impact-pgx-example"
* entry[0].resource.result[1].reference = "Observation/genotype-pgx-example"
* entry[0].resource.result[2].reference = "Observation/haplotype-1-pgx-example"
* entry[0].resource.result[3].reference = "Observation/haplotype-2-pgx-example"
* entry[0].resource.result[4].reference = "Observation/variant-1-pgx-example"
* entry[0].resource.result[5].reference = "Observation/variant-2-pgx-example"
* entry[0].resource.status = #final
* entry[0].resource.subject.reference = "Patient/patient"
* entry[1].fullUrl = "http://example.org/fhir/Patient/patient"
* entry[1].request.method = #POST
* entry[1].request.url = "Patient"
* entry[1].resource.id = "patient"
* entry[1].resource.resourceType = "Patient"
* entry[2].fullUrl = "http://example.org/fhir/Specimen/specimen"
* entry[2].request.method = #POST
* entry[2].request.url = "Patient"
* entry[2].resource.id = "specimen"
* entry[2].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/specimen"
* entry[2].resource.resourceType = "Specimen"
* entry[2].resource.subject.reference = "Patient/patient"
* entry[3].fullUrl = "http://example.org/fhir/Organization/lab"
* entry[3].request.method = #POST
* entry[3].request.url = "Organization"
* entry[3].resource.id = "lab"
* entry[3].resource.name = "Some lab"
* entry[3].resource.resourceType = "Organization"
* entry[4].fullUrl = "http://example.org/fhir/ServiceRequest/pgx-request"
* entry[4].request.method = #POST
* entry[4].request.url = "ServiceRequest"
* entry[4].resource.code.coding = http://loinc.org#81247-9
* entry[4].resource.id = "pgx-request"
* entry[4].resource.intent = #original-order
* entry[4].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/servicerequest"
* entry[4].resource.reasonCode.text = "Worried about family planning"
* entry[4].resource.resourceType = "ServiceRequest"
* entry[4].resource.status = #active
* entry[4].resource.subject.reference = "Patient/patient"
* entry[5].fullUrl = "http://example.org/fhir/Observation/med-impact-pgx-example"
* entry[5].request.method = #POST
* entry[5].request.url = "Observation"
* entry[5].resource.category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* entry[5].resource.code.coding = http://hl7.org/fhir/uv/genomics-reporting/CodeSystem/TbdCodes#therapeutic-implication "Therapeutic Implication"
* entry[5].resource.component[0].code.coding = http://loinc.org#53040-2 "Genetic variation's effect on drug metabolism"
* entry[5].resource.component[0].valueCodeableConcept.coding = http://loinc.org#LA25390-8 "Rapid metabolizer"
* entry[5].resource.component[1].code.coding = http://loinc.org#51963-7 "Medication assessed"
* entry[5].resource.component[1].valueCodeableConcept.coding = http://www.nlm.nih.gov/research/umls/rxnorm#103 "mercaptopurine"
* entry[5].resource.derivedFrom.reference = "Observation/genotype-pgx-example"
* entry[5].resource.effectiveDateTime = "2018"
* entry[5].resource.id = "med-impact-pgx-example"
* entry[5].resource.issued = "2018-03-06T00:00:00-05:00"
* entry[5].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/therapeutic-implication"
* entry[5].resource.performer.reference = "Organization/lab"
* entry[5].resource.resourceType = "Observation"
* entry[5].resource.status = #final
* entry[5].resource.subject.reference = "Patient/patient"
* entry[6].fullUrl = "http://example.org/fhir/Observation/genotype-pgx-example"
* entry[6].request.method = #POST
* entry[6].request.url = "Observation"
* entry[6].resource.category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* entry[6].resource.code.coding = http://loinc.org#84413-4 "genotype display name"
* entry[6].resource.component.code.coding = http://loinc.org#48018-6 "Gene studied ID"
* entry[6].resource.component.valueCodeableConcept.coding = http://www.genenames.org/geneId#2623 "CYP2C9"
* entry[6].resource.derivedFrom[0].reference = "Observation/haplotype-1-pgx-example"
* entry[6].resource.derivedFrom[1].reference = "Observation/haplotype-2-pgx-example"
* entry[6].resource.effectiveDateTime = "2018"
* entry[6].resource.id = "genotype-pgx-example"
* entry[6].resource.issued = "2018-03-06T00:00:00-05:00"
* entry[6].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/genotype"
* entry[6].resource.resourceType = "Observation"
* entry[6].resource.specimen.reference = "Specimen/specimen"
* entry[6].resource.status = #final
* entry[6].resource.valueCodeableConcept.coding = http://www.pharmvar.org#CYP2C9*4/*35B "CYP2C9 *4/*35B"
* entry[7].fullUrl = "http://example.org/fhir/Observation/haplotype-1-pgx-example"
* entry[7].request.method = #POST
* entry[7].request.url = "Observation"
* entry[7].resource.category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* entry[7].resource.code.coding = http://loinc.org#84414-2 "Haplotype Name"
* entry[7].resource.component.code.coding = http://loinc.org#48018-6 "Gene studied ID"
* entry[7].resource.component.valueCodeableConcept.coding = http://www.genenames.org/geneId#2623 "CYP2C9"
* entry[7].resource.derivedFrom.reference = "Observation/variant-1-pgx-example"
* entry[7].resource.effectiveDateTime = "2018"
* entry[7].resource.id = "haplotype-1-pgx-example"
* entry[7].resource.issued = "2018-03-06T00:00:00-05:00"
* entry[7].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/haplotype"
* entry[7].resource.resourceType = "Observation"
* entry[7].resource.specimen.reference = "Specimen/specimen"
* entry[7].resource.status = #final
* entry[7].resource.valueCodeableConcept.coding = http://www.pharmvar.org#CYP2C9*35B "CYP2C9 *35B"
* entry[8].fullUrl = "http://example.org/fhir/Observation/haplotype-2-pgx-example"
* entry[8].request.method = #POST
* entry[8].request.url = "Observation"
* entry[8].resource.category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* entry[8].resource.code.coding = http://loinc.org#84414-2 "Haplotype Name"
* entry[8].resource.component.code.coding = http://loinc.org#48018-6 "Gene studied ID"
* entry[8].resource.component.valueCodeableConcept.coding = http://www.genenames.org/geneId#2623 "CYP2C9"
* entry[8].resource.derivedFrom.reference = "Observation/variant-2-pgx-example"
* entry[8].resource.effectiveDateTime = "2018"
* entry[8].resource.id = "haplotype-2-pgx-example"
* entry[8].resource.issued = "2018-03-06T00:00:00-05:00"
* entry[8].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/haplotype"
* entry[8].resource.resourceType = "Observation"
* entry[8].resource.specimen.reference = "Specimen/specimen"
* entry[8].resource.status = #final
* entry[8].resource.valueCodeableConcept.coding = http://www.pharmvar.org#CYP2C9*4 "CYP2C9 *4"
* entry[9].fullUrl = "http://example.org/fhir/Observation/variant-1-pgx-example"
* entry[9].request.method = #POST
* entry[9].request.url = "Observation"
* entry[9].resource.category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* entry[9].resource.code.coding = http://loinc.org#69548-6 "Genetic variant assessment"
* entry[9].resource.component[0].code.coding = http://loinc.org#48018-6 "Gene studied ID"
* entry[9].resource.component[0].valueCodeableConcept.coding = http://www.genenames.org/geneId#2623 "CYP2C9"
* entry[9].resource.component[1].code.coding = http://loinc.org#81255-2 "dbSNP ID"
* entry[9].resource.component[1].valueCodeableConcept.coding = http://www.ncbi.nlm.nih.gov/SNP#rs12345
* entry[9].resource.component[2].code.coding = http://loinc.org#69547-8 "Ref nucleotide"
* entry[9].resource.component[2].valueString = "T"
* entry[9].resource.component[3].code.coding = http://loinc.org#69551-0 "Alt allele"
* entry[9].resource.component[3].valueString = "G"
* entry[9].resource.component[4].code.coding = http://hl7.org/fhir/uv/genomics-reporting/CodeSystem/TbdCodes#exact-start-end "Variant exact start and end"
* entry[9].resource.component[4].valueRange.high.value = 55227977
* entry[9].resource.component[4].valueRange.low.value = 55227976
* entry[9].resource.derivedFrom.reference = "MolecularSequence/sequence-1-pgx-example"
* entry[9].resource.effectiveDateTime = "2018"
* entry[9].resource.id = "variant-1-pgx-example"
* entry[9].resource.issued = "2018-03-06T00:00:00-05:00"
* entry[9].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/variant"
* entry[9].resource.resourceType = "Observation"
* entry[9].resource.specimen.reference = "Specimen/specimen"
* entry[9].resource.status = #final
* entry[9].resource.valueCodeableConcept.coding = http://loinc.org#LA9633-4 "Present"
* entry[10].fullUrl = "http://example.org/fhir/Observation/variant-2-pgx-example"
* entry[10].request.method = #POST
* entry[10].request.url = "Observation"
* entry[10].resource.category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* entry[10].resource.code.coding = http://loinc.org#69548-6 "Genetic variant assessment"
* entry[10].resource.component[0].code.coding = http://loinc.org#48018-6 "Gene studied ID"
* entry[10].resource.component[0].valueCodeableConcept.coding = http://www.genenames.org/geneId#2623 "CYP2C9"
* entry[10].resource.component[1].code.coding = http://loinc.org#48013-7 "Genomic reference sequence ID"
* entry[10].resource.component[1].valueCodeableConcept.coding = http://www.ncbi.nlm.nih.gov/nuccore#NG_007726.3
* entry[10].resource.component[2].code.coding = http://loinc.org#81255-2 "dbSNP ID"
* entry[10].resource.component[2].valueCodeableConcept.coding = http://www.ncbi.nlm.nih.gov/SNP#rs233455
* entry[10].resource.component[3].code.coding = http://loinc.org#69547-8 "Ref nucleotide"
* entry[10].resource.component[3].valueString = "T"
* entry[10].resource.component[4].code.coding = http://loinc.org#69551-0 "Alt allele"
* entry[10].resource.component[4].valueString = "G"
* entry[10].resource.component[5].code.coding = http://hl7.org/fhir/uv/genomics-reporting/CodeSystem/TbdCodes#exact-start-end "Variant exact start and end"
* entry[10].resource.component[5].valueRange.high.value = 55227979
* entry[10].resource.component[5].valueRange.low.value = 55227978
* entry[10].resource.derivedFrom.reference = "MolecularSequence/sequence-2-pgx-example"
* entry[10].resource.effectiveDateTime = "2018"
* entry[10].resource.id = "variant-2-pgx-example"
* entry[10].resource.issued = "2018-03-06T00:00:00-05:00"
* entry[10].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/variant"
* entry[10].resource.resourceType = "Observation"
* entry[10].resource.specimen.reference = "Specimen/specimen"
* entry[10].resource.status = #final
* entry[10].resource.valueCodeableConcept.coding = http://loinc.org#LA9633-4 "Present"
* entry[11].fullUrl = "http://example.org/fhir/MolecularSequence/sequence-1-pgx-example"
* entry[11].request.method = #POST
* entry[11].request.url = "MolecularSequence"
* entry[11].resource.coordinateSystem = 0
* entry[11].resource.id = "sequence-1-pgx-example"
* entry[11].resource.referenceSeq.orientation = #sense
* entry[11].resource.referenceSeq.referenceSeqId.coding = http://www.ncbi.nlm.nih.gov/nuccore#NG-007726.3
* entry[11].resource.referenceSeq.windowEnd = 55227980
* entry[11].resource.referenceSeq.windowStart = 55227970
* entry[11].resource.resourceType = "MolecularSequence"
* entry[11].resource.type = #dna
* entry[12].fullUrl = "http://example.org/fhir/MolecularSequence/sequence-2-pgx-example"
* entry[12].request.method = #POST
* entry[12].request.url = "MolecularSequence"
* entry[12].resource.coordinateSystem = 0
* entry[12].resource.id = "sequence-2-pgx-example"
* entry[12].resource.referenceSeq.orientation = #sense
* entry[12].resource.referenceSeq.referenceSeqId.coding = http://www.ncbi.nlm.nih.gov/nuccore#NG-007726.3
* entry[12].resource.referenceSeq.windowEnd = 55227980
* entry[12].resource.referenceSeq.windowStart = 55227970
* entry[12].resource.resourceType = "MolecularSequence"
* entry[12].resource.type = #dna
* entry[13].fullUrl = "http://example.org/fhir/Task/med-usage-impact-task-pgx-example"
* entry[13].request.method = #POST
* entry[13].request.url = "Task"
* entry[13].resource.code.text = "Any Increase does Recommendation Text from the provider"
* entry[13].resource.description = "Any Increase does Recommendation Text from the provider"
* entry[13].resource.focus.reference = "MedicationStatement/current-med-example"
* entry[13].resource.for.reference = "Patient/patient"
* entry[13].resource.id = "med-usage-impact-task-pgx-example"
* entry[13].resource.intent = #proposal
* entry[13].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/task-med-chg"
* entry[13].resource.reasonReference.reference = "Observation/med-impact-pgx-example"
* entry[13].resource.resourceType = "Task"
* entry[13].resource.status = #requested
* entry[14].fullUrl = "http://example.org/fhir/MedicationStatement/current-med-example"
* entry[14].request.method = #POST
* entry[14].request.url = "MedicationStatement"
* entry[14].resource.id = "current-med-example"
* entry[14].resource.medicationCodeableConcept.coding = http://www.nlm.nih.gov/research/umls/rxnorm#103 "mercaptopurine"
* entry[14].resource.resourceType = "MedicationStatement"
* entry[14].resource.status = #unknown
* entry[14].resource.subject.reference = "Patient/patient"
* id = "diagnosticreport-pgxexample"
* type = #transaction
