Instance: CGBundleExamplediagnosticreport-cgexample
InstanceOf: Bundle
Description: "Example for Bundle. "
* entry[0].fullUrl = "http://example.org/fhir/DiagnosticReport/report"
* entry[0].resource.basedOn.reference = "DiagnosticRequest/request"
* entry[0].resource.code.coding = http://loinc.org#81247-9
* entry[0].resource.effectiveDateTime = "2016"
* entry[0].resource.id = "report"
* entry[0].resource.issued = "2016-09-06T00:00:00-05:00"
* entry[0].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/genomics-report"
* entry[0].resource.performer.reference = "Organization/lab"
* entry[0].resource.presentedForm.contentType = #text/plain
* entry[0].resource.presentedForm.data = "UHV0IHRoZSByZXBvcnQgdGV4dCBoZXJlIC0gbWltZS1lbmNvZGVk"
* entry[0].resource.resourceType = "DiagnosticReport"
* entry[0].resource.result[0].reference = "Observation/overall-interp"
* entry[0].resource.result[1].reference = "Observation/discrete-variant"
* entry[0].resource.result[2].reference = "Observation/dis-path"
* entry[0].resource.result[3].reference = "Observation/complex-variant"
* entry[0].resource.result[4].reference = "Observation/complex-dis-path"
* entry[0].resource.result[5].reference = "Observation/pharmPanel"
* entry[0].resource.status = #final
* entry[0].resource.subject.reference = "Patient/patient"
* entry[1].fullUrl = "http://example.org/fhir/Patient/patient"
* entry[1].resource.id = "patient"
* entry[1].resource.resourceType = "Patient"
* entry[2].fullUrl = "http://example.org/fhir/Specimen/specimen"
* entry[2].resource.id = "specimen"
* entry[2].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/specimen"
* entry[2].resource.resourceType = "Specimen"
* entry[2].resource.subject.reference = "Patient/patient"
* entry[3].fullUrl = "http://example.org/fhir/Organization/lab"
* entry[3].resource.id = "lab"
* entry[3].resource.name = "Some lab"
* entry[3].resource.resourceType = "Organization"
* entry[4].fullUrl = "http://example.org/fhir/DiagnosticRequest/request"
* entry[4].resource.code.coding = http://loinc.org#81247-9
* entry[4].resource.id = "request"
* entry[4].resource.intent = #original-order
* entry[4].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/servicerequest"
* entry[4].resource.reasonCode.text = "Worried about family planning"
* entry[4].resource.resourceType = "ServiceRequest"
* entry[4].resource.status = #active
* entry[4].resource.subject.reference = "Patient/patient"
* entry[5].fullUrl = "http://example.org/fhir/Observation/overall-interp"
* entry[5].resource.category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* entry[5].resource.code.coding = http://loinc.org#51968-6
* entry[5].resource.effectiveDateTime = "2016"
* entry[5].resource.id = "overall-interp"
* entry[5].resource.issued = "2016-09-06T00:00:00-05:00"
* entry[5].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/overall-interpretation"
* entry[5].resource.performer.reference = "Organization/lab"
* entry[5].resource.resourceType = "Observation"
* entry[5].resource.specimen.reference = "Specimen/specimen"
* entry[5].resource.status = #final
* entry[5].resource.subject.reference = "Patient/patient"
* entry[5].resource.valueCodeableConcept.coding[0] = http://loinc.org#LA6576-8 "Positive"
* entry[5].resource.valueCodeableConcept.coding[1] = http://snomed.info/sct#10828004 "Positive"
* entry[6].fullUrl = "http://example.org/fhir/Observation/discrete-variant"
* entry[6].resource.category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* entry[6].resource.code.coding = http://loinc.org#69548-6 "Genetic variant assessment"
* entry[6].resource.component[0].code.coding = http://loinc.org#81252-9 "Discrete genetic variant"
* entry[6].resource.component[0].valueCodeableConcept.coding[0] = http://example.org/clinvar#30880 "NM_014049.4(ACAD9):c.1249C>T (p.Arg417Cys)"
* entry[6].resource.component[0].valueCodeableConcept.coding[0].version = "???"
* entry[6].resource.component[0].valueCodeableConcept.coding[1] = http://example.org/cigar#tbd
* entry[6].resource.component[1].code.coding = http://loinc.org#48018-6
* entry[6].resource.component[1].valueCodeableConcept.coding = http://example.org/hgnc#21497 "ACAD9"
* entry[6].resource.component[2].code.coding = http://loinc.org#51958-7
* entry[6].resource.component[2].valueCodeableConcept.coding = http://www.ncbi.nlm.nih.gov/refseq#NM_014049.4
* entry[6].resource.component[3].code.coding = http://loinc.org#48013-7
* entry[6].resource.component[3].valueCodeableConcept.coding = http://www.ncbi.nlm.nih.gov/refseq#NG_017064.1
* entry[6].resource.component[4].code.coding = http://loinc.org#81290-9
* entry[6].resource.component[4].valueCodeableConcept.coding = http://example.org/HGVS.g#NC_000003.11:g.128625063C>T
* entry[6].resource.component[4].valueCodeableConcept.coding.version = "15.11"
* entry[6].resource.component[5].code.coding = http://loinc.org#81255-2
* entry[6].resource.component[5].valueCodeableConcept.coding = http://example.org/dbsnp#rs368949613
* entry[6].resource.component[5].valueCodeableConcept.coding.version = "137"
* entry[6].resource.component[6].code.coding = http://loinc.org#48004-6
* entry[6].resource.component[6].valueCodeableConcept.coding = http://example.org/HGVS.c#c.1249C>T
* entry[6].resource.component[6].valueCodeableConcept.coding.version = "15.11"
* entry[6].resource.component[7].code.coding = http://loinc.org#48005-3
* entry[6].resource.component[7].valueCodeableConcept.coding = http://example.org/HGVS.p#p.Arg417Cys
* entry[6].resource.component[7].valueCodeableConcept.coding.version = "15.11"
* entry[6].resource.component[8].code.coding = http://loinc.org#48019-4
* entry[6].resource.component[8].valueCodeableConcept.coding = http://loinc.org#LA6690-7 "Substitution"
* entry[6].resource.component[9].code.coding = http://loinc.org#48006-1
* entry[6].resource.component[9].valueCodeableConcept.coding = http://loinc.org#LA6698-0 "Missense"
* entry[6].resource.component[10].code.coding = http://loinc.org#69547-8
* entry[6].resource.component[10].valueString = "C"
* entry[6].resource.component[11].code.coding = http://hl7.org/fhir/uv/genomics-reporting/CodeSystem/TbdCodes#exact-start-end
* entry[6].resource.component[11].valueRange.high.value = 31731
* entry[6].resource.component[11].valueRange.low.value = 31731
* entry[6].resource.component[12].code.coding = http://loinc.org#69551-0
* entry[6].resource.component[12].valueString = "T"
* entry[6].resource.component[13].code.coding = http://loinc.org#48001-2
* entry[6].resource.component[13].valueCodeableConcept.coding = http://example.org/Chrom-Loc#3q21
* entry[6].resource.component[14].code.coding = http://loinc.org#48002-0
* entry[6].resource.component[14].valueCodeableConcept.coding = http://loinc.org#LA6683-2 "Germline"
* entry[6].resource.component[15].code.coding = http://loinc.org#53034-5
* entry[6].resource.component[15].valueCodeableConcept.coding = http://loinc.org#LA6706-1 "Heterozygous"
* entry[6].resource.component[16].code.coding = http://loinc.org#81258-6
* entry[6].resource.component[16].valueQuantity.code = #%
* entry[6].resource.component[16].valueQuantity.system = "http://unitsofmeasure.org"
* entry[6].resource.component[16].valueQuantity.value = 47
* entry[6].resource.component[17].code.coding = http://loinc.org#82121-5
* entry[6].resource.component[17].valueQuantity.code = #1
* entry[6].resource.component[17].valueQuantity.system = "http://unitsofmeasure.org"
* entry[6].resource.component[17].valueQuantity.value = 208
* entry[6].resource.component[18].code.coding = http://loinc.org#82155-3
* entry[6].resource.component[18].valueQuantity.code = #1
* entry[6].resource.component[18].valueQuantity.system = "http://unitsofmeasure.org"
* entry[6].resource.component[18].valueQuantity.value = 1
* entry[6].resource.component[19].code.coding = http://loinc.org#81299-0
* entry[6].resource.component[19].valueQuantity.value = 0.48
* entry[6].resource.component[20].code.coding = http://loinc.org#81300-6
* entry[6].resource.component[20].valueQuantity.code = #1
* entry[6].resource.component[20].valueQuantity.system = "http://unitsofmeasure.org"
* entry[6].resource.component[20].valueQuantity.value = 1396929
* entry[6].resource.component[21].code.coding = http://loinc.org#81301-4
* entry[6].resource.component[21].valueRange.high.value = 15592000
* entry[6].resource.component[21].valueRange.low.value = 13200589
* entry[6].resource.component[22].code.coding = http://loinc.org#81302-2
* entry[6].resource.component[22].valueRange.high.value = 15581544
* entry[6].resource.component[22].valueRange.low.value = 14184616
* entry[6].resource.effectiveDateTime = "2016"
* entry[6].resource.id = "discrete-variant"
* entry[6].resource.issued = "2016-09-06T00:00:00-05:00"
* entry[6].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/variant"
* entry[6].resource.performer.reference = "Organization/lab"
* entry[6].resource.resourceType = "Observation"
* entry[6].resource.specimen.reference = "Specimen/specimen"
* entry[6].resource.status = #final
* entry[6].resource.subject.reference = "Patient/patient"
* entry[6].resource.valueCodeableConcept.coding = http://loinc.org#LA9633-4 "Present"
* entry[7].fullUrl = "http://example.org/fhir/Observation/dis-path"
* entry[7].resource.category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* entry[7].resource.code.coding = http://hl7.org/fhir/uv/genomics-reporting/CodeSystem/TbdCodes#diagnostic-implication
* entry[7].resource.component[0].code.coding = http://loinc.org#53037-8
* entry[7].resource.component[0].valueCodeableConcept.coding = http://loinc.org#LA6668-3 "Pathogenic"
* entry[7].resource.component[1].code.coding = http://loinc.org#81259-4
* entry[7].resource.component[1].valueCodeableConcept.coding = http://example.org/MedGen-Dis#C1970173 "Acyl-CoA dehydrogenase family, member 9, deficiency of"
* entry[7].resource.derivedFrom.reference = "Observation/discrete-variant"
* entry[7].resource.effectiveDateTime = "2016"
* entry[7].resource.id = "dis-path"
* entry[7].resource.issued = "2016-09-06T00:00:00-05:00"
* entry[7].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/diagnostic-implication"
* entry[7].resource.performer.reference = "Organization/lab"
* entry[7].resource.resourceType = "Observation"
* entry[7].resource.status = #final
* entry[7].resource.subject.reference = "Patient/patient"
* entry[8].fullUrl = "http://example.org/fhir/Observation/complex-variant"
* entry[8].resource.category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* entry[8].resource.code.coding = http://loinc.org#69548-6
* entry[8].resource.component.code.coding = http://loinc.org#81263-6
* entry[8].resource.component.valueCodeableConcept.coding = http://loinc.org#LA26218-0 "Haplotype"
* entry[8].resource.effectiveDateTime = "2016"
* entry[8].resource.hasMember[0].reference = "Observation/complex-component-D"
* entry[8].resource.hasMember[1].reference = "Observation/complex-component-E"
* entry[8].resource.id = "complex-variant"
* entry[8].resource.issued = "2016-09-06T00:00:00-05:00"
* entry[8].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/variant"
* entry[8].resource.performer.reference = "Organization/lab"
* entry[8].resource.resourceType = "Observation"
* entry[8].resource.specimen.reference = "Specimen/specimen"
* entry[8].resource.status = #final
* entry[8].resource.subject.reference = "Patient/patient"
* entry[8].resource.valueCodeableConcept.coding = http://loinc.org#LA9633-4 "Present"
* entry[9].fullUrl = "http://example.org/fhir/Observation/complex-dis-path"
* entry[9].resource.category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* entry[9].resource.code.coding = http://hl7.org/fhir/uv/genomics-reporting/CodeSystem/TbdCodes#diagnostic-implication
* entry[9].resource.component[0].code.coding = http://loinc.org#53037-8
* entry[9].resource.component[0].valueCodeableConcept.coding = http://loinc.org#LA6668-3 "Pathogenic"
* entry[9].resource.component[1].code.coding = http://loinc.org#81259-4
* entry[9].resource.component[1].valueCodeableConcept.coding = http://snomed.info/sct#293498008 "Debrisoquine adverse reaction (disorder)"
* entry[9].resource.derivedFrom.reference = "Observation/complex-variant"
* entry[9].resource.effectiveDateTime = "2016"
* entry[9].resource.id = "complex-dis-path"
* entry[9].resource.issued = "2016-09-06T00:00:00-05:00"
* entry[9].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/diagnostic-implication"
* entry[9].resource.performer.reference = "Organization/lab"
* entry[9].resource.resourceType = "Observation"
* entry[9].resource.status = #final
* entry[9].resource.subject.reference = "Patient/patient"
* entry[10].fullUrl = "http://example.org/fhir/Observation/complex-component-D"
* entry[10].resource.category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* entry[10].resource.code.coding = http://loinc.org#69548-6 "Genetic variant assessment"
* entry[10].resource.component[0].code.coding = http://loinc.org#81252-9 "Discrete genetic variant"
* entry[10].resource.component[0].valueCodeableConcept.coding = http://example.org/clinvar#31934 "NM_000106.5(CYP2D6):c.886C>T (p.Arg296Cys)"
* entry[10].resource.component[0].valueCodeableConcept.coding.version = "???"
* entry[10].resource.component[1].code.coding = http://loinc.org#51958-7
* entry[10].resource.component[1].valueCodeableConcept.coding = http://example.org/RefSeq-T#NM_000106.5
* entry[10].resource.component[2].code.coding = http://loinc.org#48004-6
* entry[10].resource.component[2].valueCodeableConcept.coding = http://example.org/HGVS.c#c.886C>T
* entry[10].resource.component[2].valueCodeableConcept.coding.version = "15.11"
* entry[10].resource.component[3].code.coding = http://loinc.org#48005-3
* entry[10].resource.component[3].valueCodeableConcept.coding = http://example.org/HGVS.p#p.Arg296Cys
* entry[10].resource.component[3].valueCodeableConcept.coding.version = "15.11"
* entry[10].resource.component[4].code.coding = http://loinc.org#48019-4
* entry[10].resource.component[4].valueCodeableConcept.coding = http://loinc.org#LA6690-7 "Substitution"
* entry[10].resource.component[5].code.coding = http://loinc.org#48006-1
* entry[10].resource.component[5].valueCodeableConcept.coding = http://loinc.org#LA6698-0 "Missense"
* entry[10].resource.effectiveDateTime = "2016"
* entry[10].resource.id = "complex-component-D"
* entry[10].resource.issued = "2016-09-06T00:00:00-05:00"
* entry[10].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/variant"
* entry[10].resource.performer.reference = "Organization/lab"
* entry[10].resource.resourceType = "Observation"
* entry[10].resource.specimen.reference = "Specimen/specimen"
* entry[10].resource.status = #final
* entry[10].resource.subject.reference = "Patient/patient"
* entry[10].resource.valueCodeableConcept.coding = http://loinc.org#LA9633-4 "Present"
* entry[11].fullUrl = "http://example.org/fhir/Observation/complex-component-E"
* entry[11].resource.category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* entry[11].resource.code.coding = http://loinc.org#69548-6 "Genetic variant assessment"
* entry[11].resource.component[0].code.coding = http://loinc.org#81252-9 "Discrete genetic variant"
* entry[11].resource.component[0].valueCodeableConcept.coding = http://example.org/clinvar#38486 "NM_000106.5(CYP2D6):c.1457G>C (p.Ser486Thr)"
* entry[11].resource.component[0].valueCodeableConcept.coding.version = "???"
* entry[11].resource.component[1].code.coding = http://loinc.org#51958-7
* entry[11].resource.component[1].valueCodeableConcept.coding = http://example.org/RefSeq-T#NM_000106.5
* entry[11].resource.component[2].code.coding = http://loinc.org#48004-6
* entry[11].resource.component[2].valueCodeableConcept.coding = http://example.org/HGVS.c#c.1457G>C
* entry[11].resource.component[2].valueCodeableConcept.coding.version = "15.11"
* entry[11].resource.effectiveDateTime = "2016"
* entry[11].resource.id = "complex-component-E"
* entry[11].resource.issued = "2016-09-06T00:00:00-05:00"
* entry[11].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/variant"
* entry[11].resource.performer.reference = "Organization/lab"
* entry[11].resource.resourceType = "Observation"
* entry[11].resource.specimen.reference = "Specimen/specimen"
* entry[11].resource.status = #final
* entry[11].resource.subject.reference = "Patient/patient"
* entry[11].resource.valueCodeableConcept.coding = http://loinc.org#LA9633-4 "Present"
* entry[12].fullUrl = "http://example.org/fhir/Observation/pharmPanel"
* entry[12].resource.category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* entry[12].resource.code.coding = http://hl7.org/fhir/uv/genomics-reporting/CodeSystem/TbdCodes#grouper
* entry[12].resource.effectiveDateTime = "2016"
* entry[12].resource.extension.url = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/RecommendedAction"
* entry[12].resource.extension.valueReference.reference = "Task/usage"
* entry[12].resource.hasMember[0].reference = "Observation/haplotype"
* entry[12].resource.hasMember[1].reference = "Observation/genotype"
* entry[12].resource.hasMember[2].reference = "Observation/metab"
* entry[12].resource.hasMember[3].reference = "Observation/efficacy"
* entry[12].resource.id = "pharmPanel"
* entry[12].resource.issued = "2016-09-06T00:00:00-05:00"
* entry[12].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/grouper"
* entry[12].resource.performer.reference = "Organization/lab"
* entry[12].resource.resourceType = "Observation"
* entry[12].resource.status = #final
* entry[12].resource.subject.reference = "Patient/patient"
* entry[13].fullUrl = "http://example.org/fhir/Observation/haplotype"
* entry[13].resource.category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* entry[13].resource.code.coding = http://loinc.org#84414-2
* entry[13].resource.derivedFrom.reference = "Observation/discrete-variant"
* entry[13].resource.effectiveDateTime = "2016"
* entry[13].resource.id = "haplotype"
* entry[13].resource.issued = "2016-09-06T00:00:00-05:00"
* entry[13].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/haplotype"
* entry[13].resource.performer.reference = "Organization/lab"
* entry[13].resource.resourceType = "Observation"
* entry[13].resource.specimen.reference = "Specimen/specimen"
* entry[13].resource.status = #final
* entry[13].resource.subject.reference = "Patient/patient"
* entry[13].resource.valueCodeableConcept.coding = http://example.org/???#*2
* entry[14].fullUrl = "http://example.org/fhir/Observation/genotype"
* entry[14].resource.category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* entry[14].resource.code.coding = http://loinc.org#84413-4
* entry[14].resource.component[0].code.coding = http://loinc.org#48018-6
* entry[14].resource.component[0].valueCodeableConcept.coding = http://example.org/hgnc#2623 "CYP2C9"
* entry[14].resource.component[1].code.coding = http://loinc.org#48018-6
* entry[14].resource.component[1].valueCodeableConcept.coding = http://example.org/hgnc#23663 "VKORC1"
* entry[14].resource.derivedFrom.reference = "Observation/haplotype"
* entry[14].resource.effectiveDateTime = "2016"
* entry[14].resource.id = "genotype"
* entry[14].resource.issued = "2016-09-06T00:00:00-05:00"
* entry[14].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/genotype"
* entry[14].resource.performer.reference = "Organization/lab"
* entry[14].resource.resourceType = "Observation"
* entry[14].resource.specimen.reference = "Specimen/specimen"
* entry[14].resource.status = #final
* entry[14].resource.subject.reference = "Patient/patient"
* entry[14].resource.valueCodeableConcept.coding = http://www.pharmvar.org#CYP2C9*2/*5 "CYP2C9 *2/*5"
* entry[15].fullUrl = "http://example.org/fhir/Observation/metab"
* entry[15].resource.category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* entry[15].resource.code.coding = http://hl7.org/fhir/uv/genomics-reporting/CodeSystem/TbdCodes#therapeutic-implication
* entry[15].resource.component[0].code.coding = http://loinc.org#51963-7
* entry[15].resource.component[0].valueCodeableConcept.coding = http://www.nlm.nih.gov/research/umls/rxnorm#11289 "Warfarin"
* entry[15].resource.component[1].code.coding = http://loinc.org#53040-2
* entry[15].resource.component[1].valueCodeableConcept.coding = http://loinc.org#LA25390-8 "Rapid metabolizer"
* entry[15].resource.derivedFrom.reference = "Observation/genotype"
* entry[15].resource.effectiveDateTime = "2016"
* entry[15].resource.id = "metab"
* entry[15].resource.issued = "2016-09-06T00:00:00-05:00"
* entry[15].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/therapeutic-implication"
* entry[15].resource.performer.reference = "Organization/lab"
* entry[15].resource.resourceType = "Observation"
* entry[15].resource.status = #final
* entry[15].resource.subject.reference = "Patient/patient"
* entry[16].fullUrl = "http://example.org/fhir/Observation/efficacy"
* entry[16].resource.category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* entry[16].resource.code.coding = http://hl7.org/fhir/uv/genomics-reporting/CodeSystem/TbdCodes#therapeutic-implication
* entry[16].resource.component[0].code.coding = http://loinc.org#51961-1
* entry[16].resource.component[0].valueCodeableConcept.coding = http://loinc.org#LA6676-6 "Resistant"
* entry[16].resource.component[1].code.coding = http://loinc.org#51963-7
* entry[16].resource.component[1].valueCodeableConcept.coding = http://www.nlm.nih.gov/research/umls/rxnorm#11289 "Warfarin"
* entry[16].resource.derivedFrom.reference = "Observation/genotype"
* entry[16].resource.effectiveDateTime = "2016"
* entry[16].resource.id = "efficacy"
* entry[16].resource.issued = "2016-09-06T00:00:00-05:00"
* entry[16].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/therapeutic-implication"
* entry[16].resource.performer.reference = "Organization/lab"
* entry[16].resource.resourceType = "Observation"
* entry[16].resource.status = #final
* entry[16].resource.subject.reference = "Patient/patient"
* entry[17].fullUrl = "http://example.org/fhir/Observation/highrisk"
* entry[17].resource.category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* entry[17].resource.code.coding = http://hl7.org/fhir/uv/genomics-reporting/CodeSystem/TbdCodes#therapeutic-implication
* entry[17].resource.component[0].code.coding = http://loinc.org#83009-1
* entry[17].resource.component[0].valueCodeableConcept.coding = http://loinc.org#LA19542-2 "Low risk"
* entry[17].resource.component[1].code.coding = http://loinc.org#51963-7
* entry[17].resource.component[1].valueCodeableConcept.coding = http://www.nlm.nih.gov/research/umls/rxnorm#11289 "Warfarin"
* entry[17].resource.derivedFrom.reference = "Observation/genotype"
* entry[17].resource.effectiveDateTime = "2016"
* entry[17].resource.id = "highrisk"
* entry[17].resource.issued = "2016-09-06T00:00:00-05:00"
* entry[17].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/therapeutic-implication"
* entry[17].resource.performer.reference = "Organization/lab"
* entry[17].resource.resourceType = "Observation"
* entry[17].resource.status = #final
* entry[17].resource.subject.reference = "Patient/patient"
* entry[18].fullUrl = "http://example.org/fhir/Task/usage"
* entry[18].resource.code.text = "May need higher dosage than usual."
* entry[18].resource.contained.id = "med"
* entry[18].resource.contained.medicationCodeableConcept.coding = http://www.nlm.nih.gov/research/umls/rxnorm#11289 "Warfarin"
* entry[18].resource.contained.resourceType = "MedicationStatement"
* entry[18].resource.contained.status = #unknown
* entry[18].resource.contained.subject.reference = "Patient/patient"
* entry[18].resource.focus.reference = "#med"
* entry[18].resource.for.reference = "Patient/patient"
* entry[18].resource.id = "usage"
* entry[18].resource.intent = #proposal
* entry[18].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/task-med-chg"
* entry[18].resource.reasonReference.reference = "Observation/metab"
* entry[18].resource.requester.reference = "Organization/lab"
* entry[18].resource.resourceType = "Task"
* entry[18].resource.status = #requested
* id = "diagnosticreport-cgexample"
* type = #collection
