Instance: CGBundleExamplecomplexVariant-nonHGVS
InstanceOf: Bundle
Description: "Example for Bundle. "
* entry[0].fullUrl = "urn:uuid:16fdd5fc-e665-48af-99e4-48d603f3e12d"
* entry[0].request.method = #POST
* entry[0].request.url = "Observation"
* entry[0].resource.category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* entry[0].resource.code.coding = http://loinc.org#69548-6 "Genetic variant assessment"
* entry[0].resource.component[0].code.coding = http://loinc.org#51958-7 "Transcript ref sequence ID"
* entry[0].resource.component[0].valueCodeableConcept.coding = http://www.ncbi.nlm.nih.gov/refseq#NM_022787.3 "NM_022787.3"
* entry[0].resource.component[1].code.coding = http://hl7.org/fhir/uv/genomics-reporting/CodeSystem/TbdCodes#exact-start-end "Variant exact start and end"
* entry[0].resource.component[1].valueRange.high.value = 769
* entry[0].resource.component[1].valueRange.low.value = 769
* entry[0].resource.component[2].code.coding = http://loinc.org#69547-8 "Genomic ref allele [ID]"
* entry[0].resource.component[2].valueString = "G"
* entry[0].resource.component[3].code.coding = http://loinc.org#69551-0 "Genomic alt allele [ID]"
* entry[0].resource.component[3].valueString = "A"
* entry[0].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/variant"
* entry[0].resource.resourceType = "Observation"
* entry[0].resource.status = #final
* entry[0].resource.valueCodeableConcept.coding = http://loinc.org#LA9633-4 "Present"
* entry[1].fullUrl = "urn:uuid:16fdd5fc-e665-48af-99e4-48d603f3e12e"
* entry[1].request.method = #POST
* entry[1].request.url = "Observation"
* entry[1].resource.category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* entry[1].resource.code.coding = http://loinc.org#69548-6 "Genetic variant assessment"
* entry[1].resource.component[0].code.coding = http://loinc.org#51958-7 "Transcript ref sequence ID"
* entry[1].resource.component[0].valueCodeableConcept.coding = http://www.ncbi.nlm.nih.gov/refseq#NM_022787.3 "NM_022787.3"
* entry[1].resource.component[1].code.coding = http://hl7.org/fhir/uv/genomics-reporting/CodeSystem/TbdCodes#exact-start-end "Variant exact start and end"
* entry[1].resource.component[1].valueRange.high.value = 53
* entry[1].resource.component[1].valueRange.low.value = 53
* entry[1].resource.component[2].code.coding = http://loinc.org#69547-8 "Genomic ref allele [ID]"
* entry[1].resource.component[2].valueString = "A"
* entry[1].resource.component[3].code.coding = http://loinc.org#69551-0 "Genomic alt allele [ID]"
* entry[1].resource.component[3].valueString = "G"
* entry[1].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/variant"
* entry[1].resource.resourceType = "Observation"
* entry[1].resource.status = #final
* entry[1].resource.valueCodeableConcept.coding = http://loinc.org#LA9633-4 "Present"
* entry[2].fullUrl = "urn:uuid:16fdd5fc-e665-48af-99e4-48d603f3e12a"
* entry[2].request.method = #POST
* entry[2].request.url = "Observation"
* entry[2].resource.category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* entry[2].resource.code.coding = http://loinc.org#69548-6 "Genetic variant assessment"
* entry[2].resource.component.code.coding = http://loinc.org#81263-6 "Complex Variant Type"
* entry[2].resource.component.valueCodeableConcept.coding = http://loinc.org#LA26217-2 "Compound heterozygous"
* entry[2].resource.hasMember[0].display = "unpacked representation of NM_022787.3:c.53A>G"
* entry[2].resource.hasMember[0].reference = "urn:uuid:16fdd5fc-e665-48af-99e4-48d603f3e12e"
* entry[2].resource.hasMember[1].display = "unpacked representation of NM_022787.3:c.769G>A"
* entry[2].resource.hasMember[1].reference = "urn:uuid:16fdd5fc-e665-48af-99e4-48d603f3e12d"
* entry[2].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/variant"
* entry[2].resource.resourceType = "Observation"
* entry[2].resource.status = #final
* entry[2].resource.valueCodeableConcept.coding = http://loinc.org#LA9633-4 "Present"
* id = "complexVariant-nonHGVS"
* type = #transaction
