Instance: CGBundleExampleHLAB1502-pgx-example
InstanceOf: Bundle
Description: "Example for Bundle. "
* entry[0].fullUrl = "http://example.org/fhir/DiagnosticReport/pgx-report"
* entry[0].request.method = #POST
* entry[0].request.url = "DiagnosticReport"
* entry[0].resource.basedOn.reference = "ServiceRequest/pgx-request"
* entry[0].resource.code.coding = http://loinc.org#81247-9
* entry[0].resource.effectiveDateTime = "2016"
* entry[0].resource.extension.url = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/RecommendedAction"
* entry[0].resource.extension.valueReference.reference = "Task/med-usage-impact-task-pgx-example"
* entry[0].resource.id = "pgx-report"
* entry[0].resource.issued = "2018-03-06T00:00:00-05:00"
* entry[0].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/genomics-report"
* entry[0].resource.performer.reference = "Organization/lab"
* entry[0].resource.resourceType = "DiagnosticReport"
* entry[0].resource.result[0].display = "genetics impact for high risk allele"
* entry[0].resource.result[0].reference = "Observation/medication-high-risk"
* entry[0].resource.result[1].reference = "Observation/genotype-pgx-example"
* entry[0].resource.status = #final
* entry[0].resource.subject.reference = "Patient/patient"
* entry[1].fullUrl = "http://example.org/fhir/Patient/patient"
* entry[1].request.method = #POST
* entry[1].request.url = "Patient"
* entry[1].resource.id = "patient"
* entry[1].resource.resourceType = "Patient"
* entry[2].fullUrl = "http://example.org/fhir/Specimen/specimen"
* entry[2].request.method = #POST
* entry[2].request.url = "Patient"
* entry[2].resource.id = "specimen"
* entry[2].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/specimen"
* entry[2].resource.resourceType = "Specimen"
* entry[2].resource.subject.reference = "Patient/patient"
* entry[3].fullUrl = "http://example.org/fhir/Organization/lab"
* entry[3].request.method = #POST
* entry[3].request.url = "Organization"
* entry[3].resource.id = "lab"
* entry[3].resource.name = "Some lab"
* entry[3].resource.resourceType = "Organization"
* entry[4].fullUrl = "http://example.org/fhir/ServiceRequest/pgx-request"
* entry[4].request.method = #POST
* entry[4].request.url = "ServiceRequest"
* entry[4].resource.code.coding = http://loinc.org#81247-9
* entry[4].resource.id = "pgx-request"
* entry[4].resource.intent = #original-order
* entry[4].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/servicerequest"
* entry[4].resource.reasonCode.text = "Worried about family planning"
* entry[4].resource.resourceType = "ServiceRequest"
* entry[4].resource.status = #active
* entry[4].resource.subject.reference = "Patient/patient"
* entry[5].fullUrl = "http://example.org/fhir/Observation/medication-high-risk"
* entry[5].request.method = #POST
* entry[5].request.url = "Observation"
* entry[5].resource.category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* entry[5].resource.code.coding = http://hl7.org/fhir/uv/genomics-reporting/CodeSystem/TbdCodes#therapeutic-implication "Therapeutic Implication"
* entry[5].resource.component[0].code.coding = http://loinc.org#83009-1 "Genetic variation's effect on high-risk allele"
* entry[5].resource.component[0].valueCodeableConcept.coding = http://loinc.org#LA19541-4 "High risk"
* entry[5].resource.component[1].code.coding = http://loinc.org#51963-7 "Medication assessed"
* entry[5].resource.component[1].valueCodeableConcept.coding = http://www.nlm.nih.gov/research/umls/rxnorm#2002 "Carbamazepine"
* entry[5].resource.component[2].code.coding = http://loinc.org#93044-6 "Level of evidence"
* entry[5].resource.component[2].valueCodeableConcept.coding = http://loinc.org#LA30200-2 "Very strong evidence pathogenic"
* entry[5].resource.derivedFrom.reference = "Observation/genotype-pgx-example"
* entry[5].resource.id = "medication-high-risk"
* entry[5].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/therapeutic-implication"
* entry[5].resource.resourceType = "Observation"
* entry[5].resource.status = #final
* entry[6].fullUrl = "http://example.org/fhir/Observation/genotype-pgx-example"
* entry[6].request.method = #POST
* entry[6].request.url = "Observation"
* entry[6].resource.category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* entry[6].resource.code.coding = http://loinc.org#84413-4 "genotype display name"
* entry[6].resource.component.code.coding = http://loinc.org#48018-6 "Gene studied ID"
* entry[6].resource.component.valueCodeableConcept.coding = http://www.genenames.org/geneId#HGNC:4932 "HLA-B"
* entry[6].resource.effectiveDateTime = "2018"
* entry[6].resource.id = "genotype-pgx-example"
* entry[6].resource.issued = "2018-03-06T00:00:00-05:00"
* entry[6].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/genotype"
* entry[6].resource.resourceType = "Observation"
* entry[6].resource.specimen.reference = "Specimen/specimen"
* entry[6].resource.status = #final
* entry[6].resource.valueCodeableConcept.coding = http://www.ncbi.nlm.nih.gov/clinvar#14909 "HLA-B*15:02"
* entry[7].fullUrl = "http://example.org/fhir/Task/med-usage-impact-task-pgx-example"
* entry[7].request.method = #POST
* entry[7].request.url = "Task"
* entry[7].resource.code.text = "Patients positive for this allele should not be treated with CBZ, unless the benefits clearly outweigh the risk"
* entry[7].resource.description = "Patients positive for this allele should not be treated with CBZ, unless the benefits clearly outweigh the risk. Therapy should be discontinued immediately if symptoms of SJS or TEN develop. Alternative medication should be used as first line therapy. Consideration in the choice for alternative medications should be given to potential cross-reactivity with structurally similar aromatic antiepileptic drugs such as oxcarbazepine, phenytoin, fosphenytoin and lamotrigine, which can also moderately increase risk for SJS/TEN in association with HLA-B*15:02 positivity."
* entry[7].resource.focus.reference = "MedicationStatement/current-med-example"
* entry[7].resource.for.reference = "Patient/patient"
* entry[7].resource.id = "med-usage-impact-task-pgx-example"
* entry[7].resource.intent = #proposal
* entry[7].resource.meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/task-med-chg"
* entry[7].resource.reasonReference.reference = "Observation/medication-high-risk"
* entry[7].resource.resourceType = "Task"
* entry[7].resource.status = #requested
* entry[8].fullUrl = "http://example.org/fhir/MedicationStatement/current-med-example"
* entry[8].request.method = #POST
* entry[8].request.url = "MedicationStatement"
* entry[8].resource.id = "current-med-example"
* entry[8].resource.medicationCodeableConcept.coding = http://www.nlm.nih.gov/research/umls/rxnorm#2002 "Carbamazepine"
* entry[8].resource.resourceType = "MedicationStatement"
* entry[8].resource.status = #unknown
* entry[8].resource.subject.reference = "Patient/patient"
* id = "HLAB1502-pgx-example"
* type = #transaction
