Instance: CGDiagnosticReportExamplesequence-phase-relation-CYP2C19
InstanceOf: DiagnosticReport
Description: "Example for DiagnosticReport. "
* code.text = "Genetic analysis report"
* contained[0].category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* contained[0].code.coding = http://loinc.org#69548-6 "Genetic variant assessment"
* contained[0].component[0].code.coding = http://loinc.org#62374-4 "Human reference sequence assembly version"
* contained[0].component[0].valueCodeableConcept.coding = http://loinc.org#LA14029-5 "GRCh37"
* contained[0].component[1].code.coding = http://loinc.org#48013-7 "Genomic reference sequence ID"
* contained[0].component[1].valueCodeableConcept.coding = http://www.ncbi.nlm.nih.gov/nuccore#NC_000010.10
* contained[0].component[2].code.coding = http://loinc.org#53034-5 "Allelic state"
* contained[0].component[2].valueCodeableConcept.coding = http://loinc.org#LA6706-1 "heterozygous"
* contained[0].component[3].code.coding = http://loinc.org#69547-8 "Ref nucleotide"
* contained[0].component[3].valueString = "C"
* contained[0].component[4].code.coding = http://loinc.org#69551-0 "Alt allele"
* contained[0].component[4].valueString = "A"
* contained[0].component[5].code.coding = http://loinc.org#92822-6 "Genomic coord system"
* contained[0].component[5].valueCodeableConcept.coding = http://loinc.org#LA30102-0
* contained[0].component[6].code.coding = http://hl7.org/fhir/uv/genomics-reporting/CodeSystem/TbdCodes#exact-start-end "Variant exact start and end"
* contained[0].component[6].valueRange.low.value = 96527334
* contained[0].id = "dv-5c7e9e1ca8252"
* contained[0].issued = "2019-03-05T16:04:44+00:00"
* contained[0].meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/variant"
* contained[0].resourceType = "Observation"
* contained[0].status = #final
* contained[0].valueCodeableConcept.coding = http://loinc.org#LA9633-4 "Present"
* contained[1].category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* contained[1].code.coding = http://loinc.org#69548-6 "Genetic variant assessment"
* contained[1].component[0].code.coding = http://loinc.org#62374-4 "Human reference sequence assembly version"
* contained[1].component[0].valueCodeableConcept.coding = http://loinc.org#LA14029-5 "GRCh37"
* contained[1].component[1].code.coding = http://loinc.org#48013-7 "Genomic reference sequence ID"
* contained[1].component[1].valueCodeableConcept.coding = http://www.ncbi.nlm.nih.gov/nuccore#NC_000010.10
* contained[1].component[2].code.coding = http://loinc.org#53034-5 "Allelic state"
* contained[1].component[2].valueCodeableConcept.coding = http://loinc.org#LA6706-1 "heterozygous"
* contained[1].component[3].code.coding = http://loinc.org#69547-8 "Ref nucleotide"
* contained[1].component[3].valueString = "C"
* contained[1].component[4].code.coding = http://loinc.org#69551-0 "Alt allele"
* contained[1].component[4].valueString = "G"
* contained[1].component[5].code.coding = http://loinc.org#92822-6 "Genomic coord system"
* contained[1].component[5].valueCodeableConcept.coding = http://loinc.org#LA30102-0
* contained[1].component[6].code.coding = http://hl7.org/fhir/uv/genomics-reporting/CodeSystem/TbdCodes#exact-start-end "Variant exact start and end"
* contained[1].component[6].valueRange.low.value = 96527722
* contained[1].id = "dv-5c7e9e1ca82e4"
* contained[1].issued = "2019-03-05T16:04:44+00:00"
* contained[1].meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/variant"
* contained[1].resourceType = "Observation"
* contained[1].status = #final
* contained[1].valueCodeableConcept.coding = http://loinc.org#LA9633-4 "Present"
* contained[2].category.coding = http://terminology.hl7.org/CodeSystem/observation-category#laboratory
* contained[2].code.coding = http://loinc.org#82120-7 "Allelic phase"
* contained[2].derivedFrom[0].reference = "#dv-5c7e9e1ca8252"
* contained[2].derivedFrom[1].reference = "#dv-5c7e9e1ca82e4"
* contained[2].id = "sid-5c7e9e1ca8a29"
* contained[2].issued = "2019-03-05T16:04:44+00:00"
* contained[2].meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/sequence-phase-relationship"
* contained[2].resourceType = "Observation"
* contained[2].status = #final
* contained[2].valueCodeableConcept.coding = http://hl7.org/fhir/uv/genomics-reporting/CodeSystem/seq-phase-relationship#Cis "Cis"
* id = "sequence-phase-relation-CYP2C19"
* meta.profile = "http://hl7.org/fhir/uv/genomics-reporting/StructureDefinition/genomics-report"
* result[0].reference = "#dv-5c7e9e1ca8252"
* result[1].reference = "#dv-5c7e9e1ca82e4"
* result[2].reference = "#sid-5c7e9e1ca8a29"
* status = #final
