Instance: diagnosticreport-pgxexample
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].fullUrl = "http://example.org/fhir/DiagnosticReport/pgx-report"
* entry[=].resource = pgx-report
* entry[=].request.method = #POST
* entry[=].request.url = "DiagnosticReport"
* entry[+].fullUrl = "http://example.org/fhir/Patient/ExamplePatient"
* entry[=].resource = ExamplePatient
* entry[=].request.method = #POST
* entry[=].request.url = "Patient"
* entry[+].fullUrl = "http://example.org/fhir/Specimen/specimen"
* entry[=].resource = Inline-Instance-for-diagnosticreport-pgxexample-2
* entry[=].request.method = #POST
* entry[=].request.url = "Patient"
* entry[+].fullUrl = "http://example.org/fhir/Organization/lab"
* entry[=].resource = lab
* entry[=].request.method = #POST
* entry[=].request.url = "Organization"
* entry[+].fullUrl = "http://example.org/fhir/ServiceRequest/pgx-request"
* entry[=].resource = pgx-request
* entry[=].request.method = #POST
* entry[=].request.url = "ServiceRequest"
* entry[+].fullUrl = "http://example.org/fhir/Observation/med-impact-pgx-example"
* entry[=].resource = med-impact-pgx-example
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "http://example.org/fhir/Observation/genotype-pgx-example"
* entry[=].resource = genotype-pgx-example
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "http://example.org/fhir/Observation/haplotype-1-pgx-example"
* entry[=].resource = haplotype-1-pgx-example
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "http://example.org/fhir/Observation/haplotype-2-pgx-example"
* entry[=].resource = haplotype-2-pgx-example
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "http://example.org/fhir/Observation/variant-1-pgx-example"
* entry[=].resource = variant-1-pgx-example
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "http://example.org/fhir/Observation/variant-2-pgx-example"
* entry[=].resource = variant-2-pgx-example
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "http://example.org/fhir/MolecularSequence/sequence-1-pgx-example"
* entry[=].resource = sequence-1-pgx-example
* entry[=].request.method = #POST
* entry[=].request.url = "MolecularSequence"
* entry[+].fullUrl = "http://example.org/fhir/MolecularSequence/sequence-2-pgx-example"
* entry[=].resource = sequence-2-pgx-example
* entry[=].request.method = #POST
* entry[=].request.url = "MolecularSequence"
* entry[+].fullUrl = "http://example.org/fhir/Task/med-usage-impact-task-pgx-example"
* entry[=].resource = med-usage-impact-task-pgx-example
* entry[=].request.method = #POST
* entry[=].request.url = "Task"
* entry[+].fullUrl = "http://example.org/fhir/MedicationStatement/current-med-example"
* entry[=].resource = current-med-example
* entry[=].request.method = #POST
* entry[=].request.url = "MedicationStatement"