Instance: diagnosticreport-cgexample-withGrouping
InstanceOf: Bundle
Usage: #example
* type = #collection
* entry[0].fullUrl = "http://example.org/fhir/DiagnosticReport/report-withGrouping"
* entry[=].resource = report-withGrouping
* entry[+].fullUrl = "http://example.org/fhir/Patient/ExamplePatient"
* entry[=].resource = ExamplePatient
* entry[+].fullUrl = "http://example.org/fhir/Specimen/specimen-1a"
* entry[=].resource = specimen-1a
* entry[+].fullUrl = "http://example.org/fhir/Organization/lab-1a"
* entry[=].resource = lab-1a
* entry[+].fullUrl = "http://example.org/fhir/DiagnosticRequest/request-1a"
* entry[=].resource = request-1a
* entry[+].fullUrl = "http://example.org/fhir/Observation/overall-interp-1a"
* entry[=].resource = overall-interp-1a
* entry[+].fullUrl = "http://example.org/fhir/Observation/discrete-variant"
* entry[+].fullUrl = "http://example.org/fhir/Observation/dis-path-1a"
* entry[=].resource = dis-path-1a
* entry[+].fullUrl = "http://example.org/fhir/Observation/complex-variant-1a"
* entry[=].resource = complex-variant-1a
* entry[+].fullUrl = "http://example.org/fhir/Observation/complex-dis-path-1a"
* entry[=].resource = complex-dis-path-1a
* entry[+].fullUrl = "http://example.org/fhir/Observation/complex-component-D"
* entry[+].fullUrl = "http://example.org/fhir/Observation/complex-component-E"
* entry[+].fullUrl = "http://example.org/fhir/Observation/pharmPanel-1a"
* entry[=].resource = pharmPanel-1a
* entry[+].fullUrl = "http://example.org/fhir/Observation/haplotype-1a"
* entry[=].resource = haplotype-1a
* entry[+].fullUrl = "http://example.org/fhir/Observation/genotype-1a"
* entry[=].resource = genotype-1a
* entry[+].fullUrl = "http://example.org/fhir/Observation/metab-1a"
* entry[=].resource = metab-1a
* entry[+].fullUrl = "http://example.org/fhir/Observation/efficacy-1a"
* entry[=].resource = efficacy-1a
* entry[+].fullUrl = "http://example.org/fhir/Observation/highrisk-1a"
* entry[=].resource = highrisk-1a
* entry[+].fullUrl = "http://example.org/fhir/Task/usage-1a"
* entry[=].resource = usage-1a