Instance: Inline-Instance-for-CG-IG-HLA-FullBundle-01-23
InstanceOf: MolecularSequence
Usage: #inline
* type = #dna
* coordinateSystem = 0
* referenceSeq.referenceSeqId.coding.version = "3.23"
* referenceSeq.referenceSeqId.coding = $hla#HLA00413
* referenceSeq.referenceSeqId.text = "HLA-C*03:04:01:01"
* referenceSeq.windowStart = 1001
* referenceSeq.windowEnd = 1277
* observedSeq = "GGTCTCACATCATCCAGAGGATGTATGGCTGCGACGTGGGGCCCGACGGGCGCCTCCTCCGCGGGTATGACCAGTACGCCTACGACGGCAAGGATTACATCGCCCTGAACGAGGATCTGCGCTCCTGGACCGCCGCGGACACGGCGGCTCAGATCACCCAGCGCAAGTGGGAGGCGGCCCGTGAGGCGGAGCAGCTGAGAGCCTACCTGGAGGGCCTGTGCGTGGAGTGGCTCCGCAGATACCTGAAGAATGGGAAGGAGACGCTGCAGCGCGCGG"