Instance: Inline-Instance-for-CG-IG-HLA-FullBundle-01-8
InstanceOf: MolecularSequence
Usage: #inline
* type = #dna
* coordinateSystem = 0
* referenceSeq.referenceSeqId.coding.version = "3.23"
* referenceSeq.referenceSeqId.coding = $hla#HLA00002
* referenceSeq.referenceSeqId.text = "HLA-A*01:02"
* referenceSeq.windowStart = 503
* referenceSeq.windowEnd = 773
* observedSeq = "GCTCCCACTCCATGAGGTATTTCTCCACATCCGTGTCCCGGCCCGGCAGTGGAGAGCCCCGCTTCATCGCAGTGGGCTACGTGGACGACACGCAGTTCGTGCGGTTCGACAGCGACGCCGCGAGCCAGAAGATGGAGCCGCGGGCGCCGTGGATAGAGCAGGAGGGGCCGGAGTATTGGGACCAGGAGACACGGAATATGAAGGCCCACTCACAGACTGACCGAGCGAACCTGGGGACCCTGCGCGGCTACTACAACCAGAGCGAGGACG"