Instance: oncology-report-example
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].fullUrl = "urn:uuid:fc16d84c-8584-4e1d-baae-64e2f95bfe17"
* entry[=].resource = Inline-Instance-for-oncology-report-example-1
* entry[=].request.method = #POST
* entry[=].request.url = "Organization"
* entry[=].request.ifNoneExist = "identifier=http://molit.eu/fhir/genomics/NamingSystem/organization|CEGAT"
* entry[+].fullUrl = "urn:uuid:f7a438e6-f484-453d-97e8-aa4d51008648"
* entry[=].resource = Inline-Instance-for-oncology-report-example-2
* entry[=].request.method = #POST
* entry[=].request.url = "Patient"
* entry[=].request.ifNoneExist = "identifier=http://molit.eu/fhir/genomics/NamingSystem/cegat/patID|11111"
* entry[+].fullUrl = "urn:uuid:a2041c83-b73d-4fc8-9466-4ba4a92da516"
* entry[=].resource = Inline-Instance-for-oncology-report-example-3
* entry[=].request.method = #POST
* entry[=].request.url = "Specimen"
* entry[=].request.ifNoneExist = "identifier=http://molit.eu/fhir/genomics/NamingSystem/cegat/tissueID|UNKNOWN"
* entry[+].fullUrl = "urn:uuid:dac358c3-403a-4dbb-b478-4259aed882ae"
* entry[=].resource = Inline-Instance-for-oncology-report-example-4
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "urn:uuid:1d773d66-cec7-44a2-b92a-46d00adeae00"
* entry[=].resource = Inline-Instance-for-oncology-report-example-5
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "urn:uuid:842d9ab9-d940-4f0c-adf9-e5c528f5c0e5"
* entry[=].resource = Inline-Instance-for-oncology-report-example-6
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "urn:uuid:9a9f9a4a-52e3-4738-bd0b-a25374bbf358"
* entry[=].resource = Inline-Instance-for-oncology-report-example-7
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "urn:uuid:58828523-8893-45fc-973b-16290366c5e5"
* entry[=].resource = Inline-Instance-for-oncology-report-example-8
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "urn:uuid:2c28b23f-3e9f-4c03-8c8f-0e76bc5dc9c2"
* entry[=].resource = Inline-Instance-for-oncology-report-example-9
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "urn:uuid:41bebbe5-e06f-4867-aa22-7c06db69dbd1"
* entry[=].resource = Inline-Instance-for-oncology-report-example-10
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "urn:uuid:1642f190-e2c6-4999-8040-b9b2a70618bf"
* entry[=].resource = Inline-Instance-for-oncology-report-example-11
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "urn:uuid:c3587931-242f-4129-93f9-be24500c8f29"
* entry[=].resource = Inline-Instance-for-oncology-report-example-12
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "urn:uuid:41695fc0-1fd5-4cc8-95e6-82b2848a5cb6"
* entry[=].resource = Inline-Instance-for-oncology-report-example-13
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "urn:uuid:58eb14f6-4059-4168-86a9-155ae61d30e2"
* entry[=].resource = Inline-Instance-for-oncology-report-example-14
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "urn:uuid:1a71e80f-b044-4a91-80e1-eadbe5a53dca"
* entry[=].resource = Inline-Instance-for-oncology-report-example-15
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "urn:uuid:6a80003f-822d-489e-8286-1f1dcba56dfa"
* entry[=].resource = Inline-Instance-for-oncology-report-example-16
* entry[=].request.method = #POST
* entry[=].request.url = "DiagnosticReport"