Instance: oncologyexamples-r4-withGrouping
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].fullUrl = "urn:uuid:d0b4affa-91d6-46d1-af01-b30d9f16ef6d"
* entry[=].resource = Inline-Instance-for-oncologyexamples-r4-withGrouping-1
* entry[=].request.method = #POST
* entry[=].request.url = "Patient"
* entry[+].fullUrl = "urn:uuid:a48256f8-db37-44e0-a0f6-d7af16c7c9ef"
* entry[=].resource = Inline-Instance-for-oncologyexamples-r4-withGrouping-2
* entry[=].request.method = #POST
* entry[=].request.url = "Practitioner"
* entry[+].fullUrl = "urn:uuid:a5d6a6a9-4859-480e-85b2-56974fef3b9d"
* entry[=].resource = Inline-Instance-for-oncologyexamples-r4-withGrouping-3
* entry[=].request.method = #POST
* entry[=].request.url = "Specimen"
* entry[+].fullUrl = "urn:uuid:40e85eda-4d31-4bd2-a5a0-c39d63f9824f"
* entry[=].resource = Inline-Instance-for-oncologyexamples-r4-withGrouping-4
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "urn:uuid:64b91716-6431-41bd-8fd4-7ac99bebdee9"
* entry[=].resource = Inline-Instance-for-oncologyexamples-r4-withGrouping-5
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "urn:uuid:16fdd5fc-e665-48af-99e4-48d603f3e12d"
* entry[=].resource = Inline-Instance-for-oncologyexamples-r4-withGrouping-6
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "urn:uuid:772de7d7-e1bd-4183-bdb5-cea8eda317cd"
* entry[=].resource = Inline-Instance-for-oncologyexamples-r4-withGrouping-7
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "urn:uuid:b33eb7ec-d83e-49d2-b0f3-729d024ebe01"
* entry[=].resource = Inline-Instance-for-oncologyexamples-r4-withGrouping-8
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "urn:uuid:1bf9642d-fd1c-4819-8c5d-44fae4bad524"
* entry[=].resource = Inline-Instance-for-oncologyexamples-r4-withGrouping-9
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "urn:uuid:1301943b-55db-4adf-8355-3635f7268a1b"
* entry[=].resource = Inline-Instance-for-oncologyexamples-r4-withGrouping-10
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "urn:uuid:05713d1c-0df5-46d5-a5a9-2085eef56c20"
* entry[=].resource = Inline-Instance-for-oncologyexamples-r4-withGrouping-11
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "urn:uuid:294f1401-e2eb-4df1-b6d2-09e1b7a6eca4"
* entry[=].resource = Inline-Instance-for-oncologyexamples-r4-withGrouping-12
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "urn:uuid:16fdd5fc-e665-48af-99e4-48d603f3e12f"
* entry[=].resource = Inline-Instance-for-oncologyexamples-r4-withGrouping-13
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "urn:uuid:16fdd5fc-e665-48af-99e4-48d603f3e12e"
* entry[=].resource = Inline-Instance-for-oncologyexamples-r4-withGrouping-14
* entry[=].request.method = #POST
* entry[=].request.url = "Observation"
* entry[+].fullUrl = "urn:uuid:ad7a499b-a43b-4cc8-bf46-cac62d9ecae5"
* entry[=].resource = Inline-Instance-for-oncologyexamples-r4-withGrouping-15
* entry[=].request.method = #POST
* entry[=].request.url = "DiagnosticReport"